spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/links
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web: debug
  file:
    name: "${logging.file.path}/car-washer.log"
    path: "/Users/o.yapparov"
washer:
  load-test-data: "yes"

---

management:
  endpoints:
    enabled-by-default: false
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
